version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: nestjs_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: nestjs_auth
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nestjs_network

  app:
    build: .
    container_name: nestjs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/nestjs_auth?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-here
      - STRIPE_SECRET_KEY=your-stripe-secret-key
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nestjs_network
    command: npm run start:dev

volumes:
  mongodb_data:

networks:
  nestjs_network:
    driver: bridge